### ISSUE TITLE
Webpack 2.1.0-beta.23 incompatible with angular-cli 1.0.0-beta.14

### ISSUE THREAD

**Issue by jermay** [DavideViolante/Angular2-Full-Stack#14]
Angular CLI beta 14 doesn't like the new Webpack beta 23 resulting an error when attempting to build the project as posted here:

http://stackoverflow.com/questions/39600939/invalid-configuration-object-webpack-has-been-initialised-using-a-configuration

The cats are happy once updating to CLI beta 15.

EDIT: FYI thanks for this great starter. I've been using the non CLI version and am currently migrating a project to CLI version

**Comment by DavideViolante** [comment]
Updated to Angular CLI beta 15, should be ok now.

**Comment by jermay** [comment]
Great.
