### ISSUE TITLE
path must be a string. Received null

### ISSUE THREAD

**Issue by gotti1** [DavideViolante/Angular2-Full-Stack#15]
While building the project getting error "path must be a string. Received null."  This was not coming with previous version.

**Comment by gotti1** [comment]
ng build works but ng build -w gives the error "path must be a string. Received null" TypeError: Path must be a string. Received Null at assert path (path.js:7:11)
at object.resolve (path.js: 184:7)

**Comment by DavideViolante** [comment]
Yes, this is an known issue of Angular-CLI beta 17: https://github.com/angular/angular-cli/issues/2511
You can type for now `ng build -o dist -w` while they are fixing it.

**Comment by gotti1** [comment]
Thank you, It worked.
