### ISSUE TITLE
Why not use universal?

### ISSUE THREAD

**Issue by Shyam-Chen** [DavideViolante/Angular2-Full-Stack#17]
https://github.com/angular/universal-starter

**Comment by DavideViolante** [comment]
Sorry for late response.
Yes I know about Universal and I think any app that strongly needs SEO should use Angular Universal.
Since my repo doesn't need SEO I've never thought about using Universal.
Btw I will probably try to add it to this project because I'd like to see how it works.

**Comment by rainstormza** [comment]
try universal

import 'angular2-universal-polyfills'; to app.js
error happened , 

(function (exports, require, module, __filename, __dirname) { import 'angular2-universal-polyfills';

do you have any progress about angular universal ? thanks @DavideViolante

**Comment by DavideViolante** [comment]
No, not at the moment. Try following the official getting started on:
https://github.com/angular/universal#getting-started
https://universal.angular.io/quickstart/

**Comment by rainstormza** [comment]
try this link
https://universal.angular.io/quickstart/

but it broken at the 1st line 
import 'angular2-universal/polyfills';

but I will try another way to figure it out 

thanks for your help :)

**Comment by DavideViolante** [comment]
Universal is not very stable and maintained yet, that's why I'm not trying it right now.

**Comment by Shyam-Chen** [comment]
see https://github.com/angular/angular/issues/13822
