### ISSUE TITLE
Receiving JSON insted of HTML after adding route

### ISSUE THREAD

**Issue by MojtabaGhavidel** [DavideViolante/Angular2-Full-Stack#18]
For showing problem better i created a stackoverflow question 

http://stackoverflow.com/questions/41121284/angular-2-mean-stack-receiving-json-instead-of-html

**Comment by MojtabaGhavidel** [comment]
Yeah that was it. Thanks for quick response.

I suggest add a comment in that section , it's easy to miss. 

Can i contribute?

**Comment by DavideViolante** [comment]
I don't think it's necessary :)
