### ISSUE TITLE
No webpack?

### ISSUE THREAD

**Issue by dylanh724** [DavideViolante/Angular2-Full-Stack#20]
Is this systemjs app?

**Comment by DavideViolante** [comment]
No, the project is built using Angular-CLI, that has Webpack under the hood.

**Comment by dylanh724** [comment]
Oh cheers 👍

**Comment by abubakarmani1** [comment]
@DavideViolante can you please help me out to configure Angular-CLI, Webpack under the hood.

I have mapbox-gl error [#4359 (comment)](https://github.com/mapbox/mapbox-gl-js/issues/4359#issuecomment-303880888) for exact reason. Workarounds in [#4359 (comment)](https://github.com/mapbox/mapbox-gl-js/issues/4359#issuecomment-286277540) and [#4359 (comment)](https://github.com/mapbox/mapbox-gl-js/issues/4359#issuecomment-288001933).

how can i implement these workarounds in the project???
