### ISSUE TITLE
Do you have any solution for deployment ?

### ISSUE THREAD

**Issue by rainstormza** [DavideViolante/Angular2-Full-Stack#22]
Could you please show me how to deployment both client and server file to any host ?

thanks :)

**Comment by DavideViolante** [comment]
You can deploy to Heroku for example. You need to do some changes:
- create a Procfile file and write `web: node src/server/app.js`
- edit package.json and edit `start` script with `node src/server/app.js`
- create the bundle using `ng build` or `ng build --prod` (so you have the dist folder)
- upload everything on Heroku

**Comment by rainstormza** [comment]
Did you mean ... if i change 

"start": "ng serve --proxy-config proxy.conf.json --open",
to this
"start": "node src/server/app.js",

and use command ng build for create dist folder
then upload app.js and dist folder to heroku server

that's it ?

thanks 

I've never used heroku before , so I'm very new for angular 2.
thanks for your help. :)

**Comment by DavideViolante** [comment]
Yes correct. I didn't test it, but it should work.

**Comment by rainstormza** [comment]
It doesn't work :( 
look like heroku didn't see index.html in folder dist 

Could you please try it for me ?
thanks :)

**Comment by DavideViolante** [comment]
Edit .gitignore and remove line 4. Be sure you upload to Heroku also the dist folder.
Also, I forgot to mention before, you need to use a real MongoDB server if you use Heroku, so you need to edit line 17 of app.js.

**Comment by rainstormza** [comment]
It's work !!!
thanks for your help

I'm writing the solution right now for other people that can use it easier

**Comment by rainstormza** [comment]
How to deployment this project to Heroku 
1. download source from github file "Angular2-Full-Stack-master"
2. use command cd to project and "npm install"
3. edit files in project
-file ".gitignore" delete line 4 /dist (now your dist folder can move to heroku server)
-file "package.json"  line 9 change to "start": "node src/server/app.js",
-file "app.js" in /src/server/app.js line 17 change to mongo uri "mongodb://<dbuser>:<dbpassword>@ds033259.mlab.com:33259/testt" (use mongolab to create database server)
4. try "ng serve" for testing that everything is ok
5. "ng build --prod" for build your dist folder
6. cd to your "app.js" path file and run "node app.js"
7. log will show connect to mongo and run port 3000
8. following heroku Deployment method
9. done

**Comment by varunity** [comment]
Thanks for taking the time to do this @rainstormza! I can verify that it's working for me on Heroku. My .gitignore looked a bit different(I'm probably running a slightly older version) so /dist wasn't on line 4 for me, anyway I removed the reference to /dist and was good to go.

**Comment by DavideViolante** [comment]
Istructions added to Readme.md. Thank you, closing
