### ISSUE TITLE
How are assets (images, own css,...) included to be referenced?

### ISSUE THREAD

**Issue by mpvillafranca** [DavideViolante/Angular2-Full-Stack#23]
Hi, I'm working on a project that I started with this bundle and I would like to know how to include and reference images in the html code. I've got them inside the assets folder provided in the assets/images and assets/css subfolders. When I try to reference them in the html, I'm getting an error related to the "proxy" thing.

**Comment by DavideViolante** [comment]
Mmh, the proxy thing is just for developing, to autobuild and autoreload using ng serve. Try to run your app using `node src/server/app.js` and open localhost:3000, and see if images work.
A previous version of this repo doesn't use the proxy thing, you can check that out browsing the previous commits.

**Comment by mpvillafranca** [comment]
With server on port 3000 runing, I'm getting the following now: 

```
Failed to load resource: the server responded with a status of 404 (Not Found). http://localhost:3000/images/logo.png

client?93b6:101 ./~/css-loader!./~/postcss-loader!./src/assets/css/lumen.bootstrap.min.css
Module not found: Error: Can't resolve '../fonts/glyphicons-halflings-regular.eot' in 'blsam/src/assets/css'
 @ ./~/css-loader!./~/postcss-loader!./src/assets/css/lumen.bootstrap.min.css 6:3285-3337 6:3355-3407
 @ ./src/assets/css/lumen.bootstrap.min.css
 @ multi ./~/bootstrap/dist/css/bootstrap.min.css ./~/font-awesome/css/font-awesome.min.css ./src/assets/css/lumen.bootstrap.min.css ./src/assets/css/styles.css ./src/assets/css/nomoretables.css ./~/ng2-slim-loading-bar/style.css

```

**Comment by DavideViolante** [comment]
I tried it and with proxy I cannot make it work but without you can.
1. Example img url: `<img src="./assets/images/mario.jpg" alt="mario">`
2. angular-cli.json same as this project
3. Run `ng build`, then `node src/server/app.js, then go localhost:3000.
Images works.

**Comment by rainstormza** [comment]
I think this is a server side problem
express doesn't know /images path
you have to declare it first (in app.js)

example :
app.use('/images', express.static(__dirname + '/image'));

**Comment by mpvillafranca** [comment]
Just did some tweaks to the code and now it's working for me!

My `package.json` looks like this:

```json
...
  "scripts": {
    "start": "concurrently --kill-others \"ng serve --host=0.0.0.0 --proxy-config proxy.conf.json --open\" \"npm run be\"",
    "prod": "NODE_ENV=production npm-run-series \"ng build --prod\" be",
    "be": "nodemon src/server/app.js",
    "ng": "ng",
    "lint": "tslint \"src/**/*.ts\" --project src/tsconfig.json --type-check && tslint \"e2e/**/*.ts\" --project e2e/tsconfig.json --type-check",
    "test": "ng test",
    "pree2e": "webdriver-manager update --standalone false --gecko false",
    "e2e": "protractor"
  }
...
```

Now, in the `proxy.conf.json` I'm only forwarding to my express server the API requests with this:

```json
{
  "/api": {
    "target": "http://localhost:3000",
    "secure": false
  }
}
```

Also, for production purposes, I added the bundled Angular html to my express app:

```javascript
index.get('/*', function(req, res) {
    res.sendFile(path.join(__dirname,'/../../dist/index.html'));
});
```

And configured the environment detection like this:

```javascript
const angular_routes = require('./config/routes/index');
if (config.environment == 'development'){
  app.use(errorHandler({ dumpExceptions: true, showStack: true }));
}else if(config.environment == 'production'){
  app.use(errorHandler());
  app.use('/', express.static(__dirname + '/../../dist'));
  app.use('/*', angular_routes); // all other routes are handled by Angular
}
```

So now, when I want to put an image or whatever in my Angular app I can do it as ussual. For example:

```html
<img src="assets/images/logo.png" height="40" style="margin-top: -10px;"/>
```

**Comment by DavideViolante** [comment]
I removed the proxy setting on the latest version of the project. You should not have any problem referencing images now.
