### ISSUE TITLE
tsconfig.json vs routes

### ISSUE THREAD

**Issue by avoerman** [DavideViolante/Angular2-Full-Stack#25]
I'm running into an issue with my Angular2 routes. Seems like the tsconfig.json is potentially different than what's expected:

**src/tsconfig.json**
`{ "outDir": "../dist/out-tsc" }`

while in the app.js, routes seem to be directed to /dist/index.html

**src/server/app.js**

` // all other routes are handled by Angular
  app.get('/*', function(req, res) {
    res.sendFile(path.join(__dirname,'/../../dist/index.html'));
  });
`
Or am I missing something?

**Comment by avoerman** [comment]
I'm just wondering if you're using a typescript compiler that isn't using the tsconfig.json and if so, what are the typescript configurations there?

**Comment by DavideViolante** [comment]
I haven't written tsconfig.json because this project is automatically generated using Angular-CLI. In app.js I use dist folder because is the one generated using `ng build` command.

**Comment by avoerman** [comment]
Ugh, I was thinking there was some weird typescript configurations that built the index.html and assets as well for a dev build.

ng build fixed the issue - still new to angular-cli. Thanks.
