### ISSUE TITLE
How to remove bootstrap from application?

### ISSUE THREAD

**Issue by santosh-hegde** [DavideViolante/Angular2-Full-Stack#30]
I want to use this template with my own CSS class and font files.

How can I remove bootstrap and font awesome from the application?

**Comment by DavideViolante** [comment]
Open `.angular-cli.json` file and edit lines from 21 to 30.
Open `package.json` and remove bootstrap and font awesome packages.

**Comment by viveksingh30** [comment]
npm uninstall bootstrap:4.0.0-beta.3  --no-save
